version: '3.8'

services:
  node-express-app:
    image: wildarcticfox/wild-private-repo:20.0.0
    ports: 
      - 8080:3000

  postgres:
    image: postgres:14.7-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=233377