name: Reviewer Assigned Email Notification
on:
  push:
    branches:
      - master
jobs:
  email-notification:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
    - name: Send email notification
      uses: dawidd6/action-send-mail@v2
      env:
        SMTP_SERVER: smtp.gmail.com
        SMTP_PORT: 587
        SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        MAIL_FROM: atom.of.chaos@gmail.com
        MAIL_TO: atom.of.chaos@gmail.com
        MAIL_SUBJECT: Reviewer Assigned
        MAIL_BODY: |
          A pull request has been assigned to you as a reviewer. Please review it as soon as possible.
        MAIL_DEBUG: true
